import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Sparkles, ArrowLeft, BookOpen, BarChart3, MessageCircle, Users, AlertTriangle, Heart, BookHeart, Shield, Flower2 } from "lucide-react";
import { motion } from "framer-motion";

import ReportChapter from "@/components/report/ReportChapter";
import EmotionalLandscape from "@/components/report/EmotionalLandscape";
import CrisisAlert from "@/components/report/CrisisAlert";
import ReportActions from "@/components/report/ReportActions";

export default function ReportView() {
  const navigate = useNavigate();
  const caseId = window.location.pathname.split("/").pop();

  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadReport = async () => {
      const reports = await base44.entities.Report.filter({ case_id: caseId });
      if (reports.length > 0) {
        setReport(reports[0]);
      }
      setLoading(false);
    };
    loadReport();
  }, [caseId]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-muted border-t-primary rounded-full animate-spin" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center px-6">
        <p className="text-muted-foreground mb-4">Report not found or still being generated.</p>
        <Button variant="outline" onClick={() => navigate("/dashboard")}>Go to Dashboard</Button>
      </div>
    );
  }

  return (
    <div className="w-full">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-lg mx-auto px-6 pb-20"
      >
        {/* Cover */}
        <div className="text-center mb-12 pt-8">
          <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-6">
            <BookHeart className="w-8 h-8 text-primary" />
          </div>
          <p className="text-xs text-muted-foreground uppercase tracking-widest mb-2">
            A Confidential Relationship Analysis
          </p>
          <h1 className="font-heading text-3xl md:text-4xl font-bold mb-3">
            {report.title || "Your Personal Report"}
          </h1>
          <p className="text-sm text-muted-foreground">
            Generated by Aura • {new Date(report.created_date).toLocaleDateString("en-US", { 
              year: "numeric", month: "long", day: "numeric" 
            })}
          </p>
        </div>

        {/* Crisis Alert */}
        {(report.risk_level === "crisis" || report.risk_level === "high") && <CrisisAlert />}

        <div className="bg-card rounded-2xl border border-border/60 p-6 md:p-10">
          {/* Chapter 1: Summary */}
          <ReportChapter
            number="1"
            title="Your Situation at a Glance"
            icon={BookOpen}
            content={report.summary}
          />

          <hr className="border-border/40 my-8" />

          {/* Chapter 2: Emotional Landscape */}
          <ReportChapter number="2" title="The Emotional Landscape" icon={BarChart3}>
            <EmotionalLandscape data={report.emotional_landscape} />
          </ReportChapter>

          <hr className="border-border/40 my-8" />

          {/* Chapter 3: Communication */}
          <ReportChapter
            number="3"
            title="Communication Deep Dive"
            icon={MessageCircle}
            content={report.communication_analysis}
          />

          {report.attachment_styles && (
            <div className="pl-12 mt-4 p-4 rounded-xl bg-accent/30 border border-accent">
              <p className="text-xs text-accent-foreground/70 uppercase tracking-wider mb-2">Attachment Style Insights</p>
              <p className="text-sm mb-1"><strong>Your style:</strong> {report.attachment_styles.user_style}</p>
              <p className="text-sm mb-2"><strong>Partner's style:</strong> {report.attachment_styles.partner_style}</p>
              <p className="text-sm text-muted-foreground leading-relaxed">{report.attachment_styles.explanation}</p>
            </div>
          )}

          <hr className="border-border/40 my-8" />

          {/* Chapter 4: Key Dynamics */}
          <ReportChapter
            number="4"
            title="Key Dynamics & Hidden Currents"
            icon={Users}
            content={report.key_dynamics}
          />

          {report.red_flags?.length > 0 && (
            <div className="pl-12 mt-4">
              <div className="p-4 rounded-xl bg-destructive/5 border border-destructive/20">
                <div className="flex items-center gap-2 mb-3">
                  <AlertTriangle className="w-4 h-4 text-destructive" />
                  <p className="text-sm font-medium text-destructive">Areas of Concern</p>
                </div>
                <ul className="space-y-2">
                  {report.red_flags.map((flag, i) => (
                    <li key={i} className="text-sm text-foreground/80 flex items-start gap-2">
                      <span className="text-destructive/60 mt-1">•</span>
                      {flag}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          <hr className="border-border/40 my-8" />

          {/* Chapter 5: Fatherly Advice */}
          {report.advice_type !== "motherly" && report.advice && (
            <>
              <ReportChapter
                number="5"
                title="The Path Forward: Fatherly Advice"
                icon={Heart}
                content={report.advice}
              />
              <hr className="border-border/40 my-8" />
            </>
          )}

          {/* Chapter 5b / 6: Motherly Advice */}
          {report.advice_type !== "fatherly" && report.motherly_advice && (
            <>
              <ReportChapter
                number={report.advice_type === "motherly" ? "5" : "5b"}
                title="A Mother's Heart: Nurturing Wisdom"
                icon={Flower2}
                content={report.motherly_advice}
              />
              <div className="pl-12 mt-3 mb-6">
                <p className="text-xs text-muted-foreground italic">
                  — From a woman of deep faith, married for decades, mother of three sons and a daughter
                </p>
              </div>
              <hr className="border-border/40 my-8" />
            </>
          )}

          {/* Chapter 6: Resources */}
          <ReportChapter
            number="6"
            title="Concluding Thoughts & Resources"
            icon={Shield}
            content={report.resources}
          />

          {/* Disclaimer */}
          <div className="mt-10 p-4 rounded-xl bg-muted/60 border border-border/40">
            <p className="text-xs text-muted-foreground leading-relaxed">
              <strong>Disclaimer:</strong> Aura is an AI-powered informational tool. It is not a 
              licensed human therapist, psychologist, or legal professional. The advice provided 
              is for self-reflection purposes only and is not a substitute for professional 
              psychological, medical, or legal counsel. AI systems can make mistakes. Any 
              significant decisions should be made in consultation with a qualified human professional.
            </p>
          </div>
        </div>

        {/* Post-report actions */}
        <ReportActions report={report} caseId={caseId} />

        <div className="text-center mt-8">
          <Button
            variant="outline"
            className="rounded-full px-8"
            onClick={() => navigate("/new-analysis", { state: { consents: { narrative: true, screenshots: true, media: true } } })}
          >
            Start a New Reflection
          </Button>
        </div>
      </motion.div>
    </div>
  );
}