import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, FileText } from "lucide-react";
import AuraLogo from "@/components/ui/AuraLogo";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="max-w-3xl mx-auto px-6 py-6 flex items-center gap-4">
        <Link to="/" className="text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <AuraLogo variant="wordmark" size="sm" />
      </nav>

      <div className="max-w-3xl mx-auto px-6 pb-20">
        <div className="flex items-center gap-3 mb-2">
          <FileText className="w-6 h-6 text-primary" />
          <h1 className="font-heading text-3xl font-bold">Terms of Service</h1>
        </div>
        <p className="text-sm text-muted-foreground mb-10">Last updated: April 28, 2026</p>

        <div className="space-y-8 text-foreground">

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By downloading, installing, or using <strong>Aura – Relationship AI</strong> ("Aura", "the Service"),
              you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Aura is an AI-powered relationship wellness application that provides journaling tools, emotional analysis,
              guided exercises, goal tracking, and AI-generated guidance. Aura is an <strong>informational tool only</strong> and
              is not a substitute for professional psychological, medical, legal, or relationship counseling.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">3. Eligibility</h2>
            <p className="text-muted-foreground leading-relaxed">
              You must be at least 13 years of age to use Aura. Users between 13 and 18 should have parental consent.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">4. Account Registration</h2>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>You must provide accurate, current, and complete information during registration.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must notify us immediately of any unauthorized use of your account.</li>
              <li>We reserve the right to terminate accounts that violate these Terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">5. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">You agree not to use Aura to:</p>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Submit false, misleading, or defamatory content about others.</li>
              <li>Upload content that contains malware, viruses, or malicious code.</li>
              <li>Engage in any illegal activity or facilitate harm to others.</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the Service.</li>
              <li>Use the Service to stalk or surveil another person without their consent.</li>
              <li>Violate any applicable local, national, or international law or regulation.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">6. User Content</h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain ownership of all content you submit to Aura. By submitting content, you grant us a limited,
              non-exclusive, royalty-free license to process and store your content solely to provide and improve the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">7. AI-Generated Content Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              The analysis and guidance generated by Aura are produced by artificial intelligence and are provided
              <strong> for informational and reflective purposes only</strong>. They do not constitute professional
              psychological, medical, legal, or financial advice.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-3">
              <strong>Crisis situations:</strong> If you or someone you know is in immediate danger, please contact emergency
              services (911) or a crisis hotline (e.g., 988 Suicide & Crisis Lifeline in the US) immediately.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">8. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Aura service, including its design, code, and brand, is protected by intellectual property law. You may
              not copy, modify, or distribute any part of it without our express written permission.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">9. Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your use of Aura is also governed by our{" "}
              <Link to="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link>,
              which is incorporated into these Terms by reference.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">10. Subscription & Payments</h2>
            <p className="text-muted-foreground leading-relaxed">
              Certain features may require a paid subscription. Subscriptions automatically renew unless cancelled before
              the renewal date. Refunds are handled in accordance with applicable app store policies (Google Play, Apple App Store).
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">11. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate your account at our sole discretion for conduct that violates
              these Terms or is harmful to users or the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">12. Disclaimer of Warranties</h2>
            <p className="text-muted-foreground leading-relaxed">
              THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER
              EXPRESS OR IMPLIED.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">13. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              OR CONSEQUENTIAL DAMAGES ARISING OUT OF YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">14. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may modify these Terms at any time. Continued use of the Service after changes constitutes acceptance
              of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-3">15. Contact</h2>
            <div className="p-4 rounded-xl bg-muted/40 border border-border/60 text-muted-foreground text-sm">
              <p><strong>Aura – Relationship AI</strong></p>
              <p>Email: support@theauraapp.com</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}